import React from 'react'


export const metadata = {
  title: "Expenditcher | Expenses",
  description: "Generated by create next app",
};

const Expenses = () => {
  return (
    <div>Expenses</div>
  )
}

export default Expenses