


export const metadata = {
  title: "Expenditcher | Home",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <main>
      <h2>HOME PAGE CONTENT</h2>

    </main>
  );
}
